import type { LabMaterial, MaterialSlug } from "./types";

export const materials: LabMaterial[] = [
  {
    slug: "steel",
    code: "S-01",
    name: "STEEL",
    spec: "AISI 316 · brushed · 3 mm",
    reaction: "Reflects the movement of light",
    texture: "steel",
    tone: { bg: "#17191c", fg: "#e4e7ea", accent: "#aebdc7" },
    source: {
      place: "Sheffield — Yorkshire, UK",
      coords: "53.3811° N · 1.4701° W",
      text: "Our sheet comes from a mill that has rolled steel since 1913, on a river that once turned the grinding wheels. We buy offcuts first and new coil second.",
    },
    structure: [
      { mag: "×1", title: "Surface", text: "Brushed with a 240-grit belt in a single direction. Light slides along the grain and stops across it.", pattern: "texture" },
      { mag: "×100", title: "Grain boundaries", text: "Austenitic grains, each one a separate crystal. Their borders decide how the sheet will bend.", pattern: "cells" },
      { mag: "×10⁴", title: "Lattice", text: "Face-centred cubic: iron with chromium and nickel folded in. The chromium is why it never rusts.", pattern: "lattice" },
      { mag: "×10⁷", title: "The atom", text: "At this scale steel is mostly nothing — which is, somehow, comforting.", pattern: "orbit" },
    ],
    tactility: {
      temperature: 0.12,
      hardness: 0.82,
      density: "8.0 g/cm³",
      weight: 0.86,
      text: "Cold for the first three seconds, then it borrows your temperature. Fingerprints appear and vanish like breath on a window.",
      sound: { freq: 1760, decay: 1.6, type: "sine", label: "Long, bright ring" },
    },
    application: {
      text: "We use steel where a form has to be thin and certain — and where we want the method to stay visible.",
      uses: ["Folded structures", "Hidden ballast", "Captive fixings"],
      products: ["kerf", "solen"],
    },
  },
  {
    slug: "glass",
    code: "G-02",
    name: "GLASS",
    spec: "Borosilicate · free-blown",
    reaction: "Bends whatever stands behind it",
    texture: "glass",
    tone: { bg: "#d8dddc", fg: "#0f1111", accent: "#5f7c85" },
    source: {
      place: "Murano — Venetian Lagoon, IT",
      coords: "45.4589° N · 12.3530° E",
      text: "Blown on an island whose glassmakers were once forbidden to leave it. Our maestro learned from his grandmother, who learned from hers.",
    },
    structure: [
      { mag: "×1", title: "Surface", text: "Two gathers of molten glass, blown and turned. A few seeds of air are left in, on purpose.", pattern: "texture" },
      { mag: "×50", title: "Flow lines", text: "Glass remembers how it moved. Under polarised light the whole breath of the maker is still visible.", pattern: "rings" },
      { mag: "×10⁵", title: "Random network", text: "No crystals, no order. Glass is a liquid that stopped moving — frozen mid-sentence.", pattern: "lattice" },
      { mag: "×10⁷", title: "The atom", text: "Silicon and oxygen, holding hands in no particular pattern.", pattern: "orbit" },
    ],
    tactility: {
      temperature: 0.3,
      hardness: 0.62,
      density: "2.23 g/cm³",
      weight: 0.45,
      text: "Cool and frictionless, until it isn't. Glass tells you instantly whether your hands are clean.",
      sound: { freq: 2637, decay: 1.1, type: "sine", label: "High, pure ping" },
    },
    application: {
      text: "Glass is how we hide a light source and how we show an absence.",
      uses: ["Shades that hide the source", "Vessels that hold nothing", "Diffusers"],
      products: ["vael", "solen"],
    },
  },
  {
    slug: "stone",
    code: "T-03",
    name: "STONE",
    spec: "Travertine · unfilled",
    reaction: "Shows its texture under light",
    texture: "travertine",
    tone: { bg: "#cbbda3", fg: "#1d1710", accent: "#7a5a3a" },
    source: {
      place: "Tivoli — Lazio, IT",
      coords: "41.9629° N · 12.7985° E",
      text: "Travertine forms where hot springs meet air. The quarry we buy from has been cut since the Romans built the Colosseum out of it.",
    },
    structure: [
      { mag: "×1", title: "Bedding planes", text: "Layer on layer of mineral deposit — each band a season, each gap a pause in the spring.", pattern: "texture" },
      { mag: "×20", title: "Voids", text: "Gas bubbles trapped as the stone formed. Most makers fill them. We think they're the point.", pattern: "cells" },
      { mag: "×10³", title: "Calcite crystals", text: "Rhombohedral crystals stacked like tiny, tilted bricks.", pattern: "lattice" },
      { mag: "×10⁷", title: "The atom", text: "Calcium, carbon, oxygen. The same recipe as seashells and chalk.", pattern: "orbit" },
    ],
    tactility: {
      temperature: 0.38,
      hardness: 0.55,
      density: "2.5 g/cm³",
      weight: 0.8,
      text: "Faintly chalky, faintly warm. Every void catches the edge of a fingertip.",
      sound: { freq: 220, decay: 0.25, type: "triangle", label: "Dull, short knock" },
    },
    application: {
      text: "Stone gives our objects a floor — weight you can trust and a surface that ages in public.",
      uses: ["Feet and bases", "Lids", "Counterweights"],
      products: ["vael", "solen"],
    },
  },
  {
    slug: "fabric",
    code: "F-04",
    name: "FABRIC",
    spec: "Boiled wool · 780 g/m²",
    reaction: "Gives way under your touch",
    texture: "fabric",
    tone: { bg: "#b7a386", fg: "#20170f", accent: "#7b3f22" },
    source: {
      place: "Casentino — Tuscany, IT",
      coords: "43.7270° N · 11.8111° E",
      text: "Woven, boiled, then brushed until the fibres lock together. The same valley has made this cloth for shepherds' coats since the sixteenth century.",
    },
    structure: [
      { mag: "×1", title: "Felted surface", text: "The weave disappears under a fog of fibres — that's the boiling at work.", pattern: "texture" },
      { mag: "×40", title: "Weave", text: "A 2/2 twill, over-two under-two, before it's shrunk by a third.", pattern: "fibres" },
      { mag: "×400", title: "Fibre scales", text: "Each wool fibre is covered in tiny scales. Heat makes them hook onto each other forever.", pattern: "cells" },
      { mag: "×10⁷", title: "The atom", text: "Keratin — the same protein as your hair. It's a very close relative.", pattern: "orbit" },
    ],
    tactility: {
      temperature: 0.9,
      hardness: 0.08,
      density: "0.4 g/cm³",
      weight: 0.15,
      text: "Warm on contact, dense, a little resistant. It feels like it has already been worn by someone kind.",
      sound: { freq: 96, decay: 0.12, type: "triangle", label: "Muffled, almost silent" },
    },
    application: {
      text: "Fabric is where our objects meet bodies — so it has to be honest, repairable and warm.",
      uses: ["Upholstery", "Felt pads", "Acoustic linings"],
      products: ["halden", "solen"],
    },
  },
  {
    slug: "wood",
    code: "W-05",
    name: "WOOD",
    spec: "Rift-sawn European oak",
    reaction: "Reveals its grain",
    texture: "wood",
    tone: { bg: "#7e5f40", fg: "#f3e9dc", accent: "#e3bd8c" },
    source: {
      place: "Spessart — Bavaria, DE",
      coords: "50.0000° N · 9.4000° E",
      text: "Oak from a forest managed by the same families for eleven generations. We buy trees, not boards — and we know which ones.",
    },
    structure: [
      { mag: "×1", title: "Grain", text: "Rift-sawn: cut at 45° to the rings, so the grain runs dead straight.", pattern: "texture" },
      { mag: "×10", title: "Growth rings", text: "Every ring a year. Our oldest leg remembers a winter in 1841.", pattern: "rings" },
      { mag: "×200", title: "Vessels & rays", text: "Channels that once carried water from roots to leaves, now carrying light across a surface.", pattern: "cells" },
      { mag: "×10⁷", title: "The atom", text: "Carbon, pulled out of the air one breath at a time.", pattern: "orbit" },
    ],
    tactility: {
      temperature: 0.75,
      hardness: 0.45,
      density: "0.72 g/cm³",
      weight: 0.4,
      text: "Warm, faintly ridged along the grain. Oiled oak feels like skin that has spent time outdoors.",
      sound: { freq: 440, decay: 0.18, type: "triangle", label: "Warm, woody tock" },
    },
    application: {
      text: "Wood is our structure of choice whenever an object will be touched every day.",
      uses: ["Frames", "Joinery", "Cork (the bark)"],
      products: ["halden", "kerf"],
    },
  },
  {
    slug: "composite",
    code: "C-06",
    name: "COMPOSITE",
    spec: "Flax fibre · bio-resin",
    reaction: "Opens its layers",
    texture: "composite",
    tone: { bg: "#1d1c19", fg: "#e7e2d7", accent: "#c7aa74" },
    source: {
      place: "Normandy — FR",
      coords: "49.1829° N · 0.3707° W",
      text: "Flax grows in the wet coastal fields of Normandy. We lay its fibres in a plant-based resin to make panels lighter than aluminium.",
    },
    structure: [
      { mag: "×1", title: "Twill", text: "A satin twill pattern — the only decoration is the order of the fibres.", pattern: "texture" },
      { mag: "×50", title: "Plies", text: "Eleven layers, each rotated 45°. Strength comes from disagreement.", pattern: "fibres" },
      { mag: "×500", title: "Fibre bundles", text: "Hollow flax cells, packed like a bundle of straws.", pattern: "cells" },
      { mag: "×10⁷", title: "The atom", text: "Cellulose — the most common organic polymer on Earth.", pattern: "orbit" },
    ],
    tactility: {
      temperature: 0.55,
      hardness: 0.7,
      density: "1.3 g/cm³",
      weight: 0.3,
      text: "Satin under the fingers, surprisingly light. It feels engineered and grown at the same time.",
      sound: { freq: 660, decay: 0.35, type: "square", label: "Tight, dry snap" },
    },
    application: {
      text: "Composites are where we test the future — structures that grow before they are built.",
      uses: ["Future prototypes", "Glides & gaskets", "Structural shells"],
      products: ["kerf", "halden"],
    },
  },
];

export const getMaterial = (slug: string) => materials.find((m) => m.slug === (slug as MaterialSlug));
